import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import "./globals.css";
import Responsive from "./components/Navigation/Responsive";
import Footer from "./components/Footer/Footer";

const poppins = Poppins({
  weight: ["400", "500", "600", "700", "800"],
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Agency | Build Your Dream",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={poppins.className}>
        <Responsive />
        {children}
        <Footer />
      </body>
    </html>
  );
}
